# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{crags}
  s.version = "1.7.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Justin Marney"]
  s.date = %q{2010-07-18}
  s.description = %q{A library to help search across multiple craigslist locations.}
  s.email = %q{gotascii@gmail.com}
  s.extra_rdoc_files = [
    "LICENSE",
     "README.rdoc",
     "TODO"
  ]
  s.files = [
    ".gitignore",
     "Gemfile",
     "LICENSE",
     "README.rdoc",
     "Rakefile",
     "TODO",
     "VERSION",
     "crags.gemspec",
     "lib/crags.rb",
     "lib/crags/fetch.rb",
     "lib/crags/runner.rb",
     "lib/crags/searcher.rb",
     "spec/crags/fetch_spec.rb",
     "spec/crags/runner_spec.rb",
     "spec/crags/searcher_spec.rb",
     "spec/spec_helper.rb"
  ]
  s.homepage = %q{http://github.com/gotascii/crags}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.6}
  s.summary = %q{A library to help search across multiple craigslist locations.}
  s.test_files = [
    "spec/crags/fetch_spec.rb",
     "spec/crags/runner_spec.rb",
     "spec/crags/searcher_spec.rb",
     "spec/spec_helper.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
    else
    end
  else
  end
end

